# Generated by Django 4.2.7 on 2023-11-28 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название', max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название', max_length=100, verbose_name='Название')),
                ('description', models.CharField(help_text='Введите краткое описание', max_length=1000, verbose_name='Краткое описание')),
                ('proteins', models.FloatField(default=0, help_text='Введите белки в граммах', verbose_name='Белки, грамм')),
                ('fats', models.FloatField(default=0, help_text='Введите жиры в граммах', verbose_name='Жиры, грамм')),
                ('carbohydrates', models.FloatField(default=0, help_text='Введите углеводы в граммах', verbose_name='Углеводы, грамм')),
                ('calories', models.FloatField(default=0, help_text='Введите калории, ккал', verbose_name='Калории, ккал')),
                ('breakfast', models.BooleanField(default=False, help_text='Подходит для завтрака', verbose_name='Подходит для завтрака')),
                ('lunch', models.BooleanField(default=False, help_text='Подходит для обеда', verbose_name='Подходит для обеда')),
                ('dinner', models.BooleanField(default=False, help_text='Подходит для ужина', verbose_name='Подходит для ужина')),
                ('usualdiet', models.BooleanField(default=False, help_text='Подходит для обычного питания', verbose_name='Подходит для обычного питания')),
                ('weightloss', models.BooleanField(default=False, help_text='Подходит для похудения', verbose_name='Подходит для похудения')),
                ('weightgain', models.BooleanField(default=False, help_text='Подходит для набора веса', verbose_name='Подходит для набора веса')),
                ('recipe', models.TextField(help_text='Напишите рецепт приготовления', verbose_name='Рецепт')),
                ('time', models.CharField(default='Не указано', help_text='Укажите время готовки', max_length=100, verbose_name='Время готовки')),
                ('modercheck', models.BooleanField(default=False, help_text='Проверено модератором', verbose_name='Проверено модератором')),
                ('mainphoto', models.ImageField(blank=True, help_text='Выберите главное фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo1', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo3', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo4', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo5', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo6', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo7', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo8', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('photo9', models.ImageField(blank=True, help_text='Выберите фото блюда', null=True, upload_to='dish/', verbose_name='Фото')),
                ('cookware', models.ManyToManyField(blank=True, help_text='Выберите необходимую посуду для готовки', related_name='cookware', to='dishapp.cookware', verbose_name='Необходимая посуда')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_creator', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, help_text='Выберите пользователей, которым ненравится это блюдо', related_name='dish_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым ненравится это блюдо')),
                ('likes', models.ManyToManyField(blank=True, help_text='Выберите пользователей, которым нравится это блюдо', related_name='dish_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится это блюдо')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Напишите отзыв', verbose_name='Отзыв')),
                ('date_review', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название', max_length=100, verbose_name='Название')),
                ('price', models.FloatField(default=0, help_text='Введите цену (за шт/кг)', verbose_name='Цена (за шт/кг)')),
                ('image', models.ImageField(blank=True, help_text='Выберите фото ингредиента', null=True, upload_to='ingredient/', verbose_name='Фото')),
                ('users_ban', models.ManyToManyField(blank=True, help_text='Выберите пользователей, которые не хотят видеть этот ингредиент в блюдах', related_name='user_ban_ingredient', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые не хотят видеть этот ингредиент в блюдах')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='Не указано', help_text='Укажите кол-во', max_length=100, verbose_name='Кол-во')),
                ('dish', models.ForeignKey(help_text='Выберите блюдо', on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='dishapp.dish', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(help_text='Выберите ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingregient', to='dishapp.ingredient', verbose_name='Ингредиент')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='dishapp.review', verbose_name='Отзывы'),
        ),
    ]
