# Generated by Django 4.2.7 on 2023-11-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='users_ban',
            field=models.ManyToManyField(blank=True, help_text='Выберите пользователей, которые не хотят видеть этот ингредиент в блюдах', related_name='user_ban_ingredient', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые не хотят видеть этот ингредиент в блюдах'),
        ),
        migrations.AddField(
            model_name='dishingredients',
            name='dish',
            field=models.ForeignKey(help_text='Выберите блюдо', on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='dishapp.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dishingredients',
            name='ingredient',
            field=models.ForeignKey(help_text='Выберите ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingregient', to='dishapp.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cookware',
            field=models.ManyToManyField(blank=True, help_text='Выберите необходимую посуду для готовки', related_name='cookware', to='dishapp.cookware', verbose_name='Необходимая посуда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='dislikes',
            field=models.ManyToManyField(blank=True, help_text='Выберите пользователей, которым ненравится это блюдо', related_name='dish_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым ненравится это блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Выберите пользователей, которым нравится это блюдо', related_name='dish_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится это блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='dishapp.review', verbose_name='Отзывы'),
        ),
    ]
