# Generated by Django 5.0 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='in_algorithm',
            field=models.BooleanField(default=False, help_text='Будет ли это блюдо учитываться алгоритмом', verbose_name='Блюдо в алгоритме'),
        ),
    ]
