# Generated by Django 4.2.7 on 2023-11-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
    ]
