# Generated by Django 4.2.7 on 2023-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0003_remove_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='other_names',
            field=models.TextField(help_text='Введите другие названия', null=True, verbose_name='Другие названия'),
        ),
    ]
