# Generated by Django 5.0 on 2024-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0003_dish_in_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='last_update_price',
            field=models.DateField(blank=True, null=True),
        ),
    ]
