# Generated by Django 4.2.7 on 2023-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0004_ingredient_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_update_price',
            field=models.DateField(null=True),
        ),
    ]
