# Generated by Django 5.0 on 2024-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0005_ingredient_calories_ingredient_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(blank=True, default=0, help_text='Введите калории (на 100 гр)', null=True, verbose_name='Калории (на 100 гр)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(blank=True, default=0, help_text='Введите углеводы в гр (на 100 гр)', null=True, verbose_name='Углеводы (на 100 гр)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(blank=True, default=0, help_text='Введите жиры в гр (на 100 гр)', null=True, verbose_name='Жиры (на 100 гр)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(blank=True, default=0, help_text='Введите белки в гр (на 100 гр)', null=True, verbose_name='Белки (на 100 гр)'),
        ),
    ]
