# Generated by Django 5.0 on 2024-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='physical_activity',
            field=models.CharField(choices=[('minimum', 'Минимальные нагрузки (сидячая работа)'), ('training3', 'Необременительные тренировки 3 раза в неделю (частые пешие прогулки)'), ('training5', 'Тренировки 5 раз в неделю (работа средней тяжести)'), ('intensetraining5', 'Интенсивные тренировки 5 раз в неделю'), ('everydaytraining', 'Ежедневные тренировки'), ('everydayintense', 'Ежедневные интенсивные тренировки или занятия 2 раза в день'), ('maximum', 'Тяжелая физическая работа или интенсивные тренировки 2 раза в день')], default='training3', help_text='Выберите свою физическую активность', max_length=400, verbose_name='Физическая активность'),
        ),
    ]
