# Generated by Django 5.0 on 2024-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_physical_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='physical_activity',
            field=models.CharField(choices=[('minimum', 'Минимальные нагрузки (сидячая работа)'), ('training3', 'Легкие тренировки или пешие прогулки 1-3 раза в неделю'), ('training5', 'Тренировки или работа средней тяжести 3-5 раз в неделю'), ('intensetraining5', 'Тренировки или тяжелая работа 5-7 раз в неделю'), ('maximum', 'Тренировки или тяжелая работа каждый день')], default='training3', help_text='Выберите свою физическую активность', max_length=400, verbose_name='Физическая активность'),
        ),
    ]
