# Generated by Django 4.2.7 on 2023-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите фото профиля', null=True, upload_to='user/', verbose_name='Фото'),
        ),
    ]
