# Generated by Django 5.0 on 2024-03-12 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_menu_dateend_alter_menu_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dateend',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 17, 18, 22, 0, 220696), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='datestart',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 11, 18, 22, 0, 220696), null=True),
        ),
    ]
