# Generated by Django 5.0 on 2024-03-12 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_menu_dateend_alter_menu_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dateend',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='datestart',
            field=models.DateField(default=datetime.date(2024, 3, 11)),
        ),
    ]
