# Generated by Django 5.0 on 2024-03-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_menu_dateend_alter_menu_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='info',
            field=models.CharField(blank=True, help_text='Дополнительная информация', max_length=1000, null=True, verbose_name='Информация'),
        ),
    ]
