# Generated by Django 5.0 on 2024-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0006_alter_ingredient_calories_and_more'),
        ('mainapp', '0007_menu_cookware_menu_diet_alter_menu_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='blacklist',
            field=models.ManyToManyField(blank=True, help_text='Блюда, которые уже заменяли', related_name='blacklist', to='dishapp.dish', verbose_name='Исключенные блюда'),
        ),
    ]
