# Generated by Django 4.2.7 on 2023-12-01 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_menu_dateend_alter_menu_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dateend',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 12, 56, 37, 4424)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='datestart',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 12, 56, 37, 3424)),
        ),
    ]
